import { CartItem, useCart } from "@/contexts/CartContext";
import { applyColorTheme } from "@/lib/applyColorTheme";
import { trpc } from "@/lib/trpc";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import WhatsAppButton from "@/components/WhatsAppButton";
import CartPanel from "@/components/CartPanel";
import CategoryRail from "@/components/CategoryRail";
import EmptyMenu from "@/components/EmptyMenu";
import ProductDialog from "@/components/ProductDialog";
import PromotionStrip from "@/components/PromotionStrip";
import ServiceSection from "@/components/ServiceSection";
import ThemeSwitcher from "@/components/ThemeSwitcher";
import { ArrowRight, Clock3, MapPin, PauseCircle, Search, ShoppingBag, Wallet } from "lucide-react";
import { isMarcaBackground, MARCA_GRADIENT } from "@shared/colorThemes";
import { useTheme } from "@/contexts/ThemeContext";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import type { MenuCategory, MenuProduct } from "@/lib/menuTypes";

export { default as ThemeSwitcher } from "@/components/ThemeSwitcher";

const money = (cents: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100);

export default function Home() {
  const [, setLocation] = useLocation(); const { itemCount } = useCart(); const { theme } = useTheme(); const [selected, setSelected] = useState<MenuProduct | null>(null); const [editingItem, setEditingItem] = useState<CartItem | null>(null); const [cartOpen, setCartOpen] = useState(false); const [justAdded, setJustAdded] = useState<string | null>(null);
  useEffect(() => { const handleCartUpdate = (event: Event) => setJustAdded((event as CustomEvent<{ name: string }>).detail.name); window.addEventListener("mm:cart-updated", handleCartUpdate); return () => window.removeEventListener("mm:cart-updated", handleCartUpdate); }, []);
  const settings = trpc.catalog.settings.useQuery(); const catalog = trpc.catalog.list.useQuery();
  useEffect(() => { applyColorTheme(settings.data?.colorTheme, settings.data?.customBackgroundColor); }, [settings.data?.colorTheme, settings.data?.customBackgroundColor]);
  const categories = (catalog.data ?? []) as MenuCategory[];
  const marca = isMarcaBackground(settings.data?.customBackgroundColor);
  const hasCustomBg = Boolean(settings.data?.customBackgroundColor);
  if (settings.isLoading || catalog.isLoading) return <div className="grid min-h-screen place-items-center bg-background"><div className="text-center"><div className="mx-auto mb-4 h-8 w-8 animate-spin rounded-full border-2 border-primary border-t-transparent" /><p className="text-sm text-muted-foreground">Preparando o cardápio…</p></div></div>;
  if (settings.error || catalog.error) return <div className="grid min-h-screen place-items-center px-6 text-center"><div><h1 className="font-display text-3xl">Não foi possível abrir o cardápio.</h1><p className="mt-3 text-muted-foreground">Atualize a página em alguns instantes.</p></div></div>;
  return <div className={`mm-storefront min-h-screen overflow-x-hidden ${theme === "dark" ? "theme-dark" : "theme-light"}`} style={marca ? { background: MARCA_GRADIENT } : undefined}><header className={`sticky top-0 z-40 border-b border-white/15 backdrop-blur ${marca ? "text-[#fffaf3]" : hasCustomBg ? "border-foreground/15 text-foreground" : "bg-[#15120f]/95 text-[#fffaf3]"}`} style={marca ? { background: MARCA_GRADIENT } : hasCustomBg ? { background: "color-mix(in srgb, var(--primary) 16%, var(--background))", borderBottom: "3px solid var(--primary)" } : undefined}><div className={`page-shell flex min-h-14 items-center justify-between gap-3 py-2 sm:min-h-16 ${marca ? "sm:py-5" : "sm:py-3"}`}><div className="flex min-w-0 flex-col items-start gap-1 sm:gap-2"><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="flex items-center gap-1.5 sm:gap-2"><img src={settings.data?.logoUrl || "/comandiva-icon.png"} alt="Logotipo Comandiva" className="h-7 w-7 shrink-0 object-contain sm:h-10 sm:w-10" /><span className="font-display text-base font-bold tracking-tight sm:text-xl">Comandiva</span></button><ThemeSwitcher onTintedChrome={hasCustomBg && !marca} /></div><div className="flex items-center gap-2 sm:gap-3"><button onClick={() => setLocation("/acompanhar")} className={`hidden text-sm font-medium sm:block ${marca || !hasCustomBg ? "text-[#e6d9c8] hover:text-white" : "font-semibold text-foreground hover:text-primary"}`}>Acompanhar pedido</button><button onClick={() => setLocation("/acompanhar")} aria-label="Acompanhar pedido" className={`rounded-xl border p-2.5 transition sm:hidden ${marca || !hasCustomBg ? "border-white/15 text-[#e6d9c8] hover:bg-white/10 hover:text-white" : "border-foreground/25 text-foreground hover:bg-foreground/10"}`}><Search className="h-5 w-5" /></button><button onClick={() => setCartOpen(true)} className="relative rounded-xl bg-primary p-2.5 transition hover:bg-primary-hover-light" style={marca ? { background: MARCA_GRADIENT } : undefined} aria-label="Abrir sacola"><ShoppingBag className="h-5 w-5" />{itemCount > 0 && <span className="absolute -right-2 -top-2 grid h-5 min-w-5 place-items-center rounded-full bg-[#e9c98f] px-1 text-[11px] font-bold text-[#261a0f]">{itemCount}</span>}</button></div></div></header>
    {settings.data && !settings.data.isAcceptingOrders && <div className="bg-amber-100 px-4 py-2.5 text-center text-sm font-semibold text-amber-900"><PauseCircle className="mr-1.5 inline h-4 w-4 -translate-y-px" />No momento não estamos recebendo novos pedidos. Volte em instantes.</div>}
    <main><section className="relative isolate min-h-[160px] overflow-hidden bg-[#15120f] text-[#fffaf3] sm:min-h-[380px]"><div className="absolute inset-0 opacity-70"><img src="/assets/pubx/hero-brand-burger-v2.webp" alt="" aria-hidden="true" fetchPriority="high" className="h-full w-full object-cover object-[92%_center] sm:object-[78%_22%]" /></div><div className="absolute inset-0 bg-gradient-to-r from-[#15120f] via-[#15120f]/85 to-[#15120f]/25" /><div className="page-shell relative flex min-h-[160px] flex-col justify-center py-4 sm:min-h-[380px] sm:py-12"><Badge className="w-fit rounded-full border border-[#e9c98f]/40 bg-[#e9c98f]/10 px-2.5 py-0.5 text-[10px] font-medium text-[#f1d7aa] sm:px-3 sm:py-1 sm:text-xs">Cozinha aberta · {settings.data?.openingHours}</Badge><h1 className="mt-2 max-w-xl font-display text-lg font-bold leading-[1.15] tracking-tight sm:mt-4 sm:text-4xl">Seu <span className="text-[#e9c98f]">próximo sabor favorito</span> está aqui.</h1><p className="mt-1.5 max-w-md text-[11px] leading-4 text-[#ded0bc] sm:mt-3 sm:text-sm sm:leading-5">Hambúrgueres, pizzas, porções e pratos preparados para deixar sua refeição ainda mais especial.</p><div className="mt-2 flex flex-wrap gap-2 text-[10px] sm:mt-4 sm:gap-4 sm:text-sm"><span className="flex items-center gap-1"><Clock3 className="h-3 w-3 text-[#e9c98f] sm:h-4 sm:w-4" />{settings.data?.estimatedDeliveryMin}–{settings.data?.estimatedDeliveryMax} min</span><span className="flex items-center gap-1"><MapPin className="h-3 w-3 text-[#e9c98f] sm:h-4 sm:w-4" />Delivery e retirada</span>{Boolean(settings.data?.minimumOrderCents) && <span className="flex items-center gap-1"><Wallet className="h-3 w-3 text-[#e9c98f] sm:h-4 sm:w-4" />Pedido mínimo {money(settings.data!.minimumOrderCents)}</span>}</div><Button onClick={() => document.getElementById("cardapio")?.scrollIntoView({ behavior: "smooth" })} className="mt-3 h-8 w-fit rounded-xl bg-primary px-4 text-xs hover:bg-primary-hover-light sm:mt-5 sm:h-11 sm:px-6 sm:text-base" style={marca ? { background: MARCA_GRADIENT } : undefined}>Ver cardápio <ArrowRight className="ml-2 h-3.5 w-3.5 sm:h-4 sm:w-4" /></Button></div></section>
      <PromotionStrip categories={categories} onSelectProduct={setSelected} />{categories.length ? <CategoryRail categories={categories} onSelect={setSelected} /> : <EmptyMenu openingHours={settings.data?.openingHours} />}<ServiceSection />
    </main><footer className="bg-[#15120f] py-9 text-[#d5c8b6]"><div className="page-shell flex flex-col gap-6"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div><p className="font-display text-xl font-bold text-[#fffaf3]">Comandiva</p><p className="mt-1 text-sm">Pedidos preparados com atenção.</p></div><div className="flex flex-col gap-2 text-xs sm:items-end"><button onClick={() => setLocation("/painel-pedidos")} className="text-left text-[#978a79] transition hover:text-[#e9c98f]">Painel de pedidos da equipe</button><div className="flex flex-wrap justify-end gap-4"><a href="/sobre" className="text-[#978a79] transition hover:text-[#e9c98f]">Sobre</a><a href="/faq" className="text-[#978a79] transition hover:text-[#e9c98f]">Perguntas frequentes</a><a href="/politica-de-privacidade" className="text-[#978a79] transition hover:text-[#e9c98f]">Política de Privacidade</a><a href="/termos-de-uso" className="text-[#978a79] transition hover:text-[#e9c98f]">Termos de Uso</a></div></div></div><div className="border-t border-[#2c241a] pt-5 text-center text-[11px] leading-5 text-[#7a6c5c]"><p>© {new Date().getFullYear()} Comandiva — Todos os direitos reservados.</p><p className="mt-1">Criador: Maycon Meneses · WhatsApp: (88) 99940-1565</p></div></div></footer>
    <WhatsAppButton phone={settings.data?.phone} />
    <ProductDialog product={selected} editingItem={editingItem} open={Boolean(selected)} onOpenChange={open => { if (!open) { setSelected(null); setEditingItem(null); } }} />
    <Dialog open={Boolean(justAdded)} onOpenChange={open => { if (!open) setJustAdded(null); }}><DialogContent className="mm-success-dialog max-w-sm rounded-2xl border-0 p-6"><DialogHeader><div className="grid h-11 w-11 place-items-center rounded-full bg-[#f6e6da] text-primary"><ShoppingBag className="h-5 w-5" /></div><DialogTitle className="mt-4 font-display text-3xl">Item adicionado</DialogTitle><p className="mt-2 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">{justAdded}</strong> está na sua sacola. Deseja escolher mais itens ou finalizar o pedido?</p></DialogHeader><div className="mt-6 grid gap-3"><Button variant="outline" onClick={() => setJustAdded(null)} className="h-11 rounded-xl bg-[#fffdf8] text-[#231d18]">Continuar comprando</Button><Button onClick={() => { setJustAdded(null); setCartOpen(true); }} className="h-11 rounded-xl bg-primary hover:bg-primary-hover">Ir para o carrinho <ArrowRight className="ml-2 h-4 w-4" /></Button></div></DialogContent></Dialog>
    {cartOpen && <><button className="fixed inset-0 z-40 bg-black/40" aria-label="Fechar sacola" onClick={() => setCartOpen(false)} /><CartPanel onClose={() => setCartOpen(false)} deliveryFeeCents={settings.data?.deliveryFeeCents ?? 0} onEdit={item => { const product = catalog.data?.flatMap(category => category.products).find(productRow => productRow.id === item.productId); if (product) { setEditingItem(item); setSelected(product); setCartOpen(false); } }} /></>}
  </div>;
}
