import { trpc } from "@/lib/trpc";
import { CircleDollarSign, ClipboardList, Clock3, ShoppingBag } from "lucide-react";
import { Header, Loading, money } from "./shared";
import OperationSettings from "./OperationSettings";
import OrdersTable from "./OrdersTable";

export default function Overview() {
  const dashboard = trpc.admin.dashboard.useQuery(); if (dashboard.isLoading) return <Loading />; if (dashboard.error) return <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{dashboard.error.message}</p>;
  const values = dashboard.data?.metrics;
  return <><Header eyebrow="Operação em tempo real" title="Boa noite, equipe." description="Acompanhe a operação do MM System Creator e mantenha o fluxo de pedidos sob controle." action={<div className="flex flex-wrap items-center gap-2"><div className="flex items-center gap-2 rounded-full border border-[#d8c7b0] bg-[#fffdf8] px-3 py-2 text-xs font-semibold text-[#5e5144]"><span className={`h-2 w-2 rounded-full ${dashboard.data?.settings?.isAcceptingOrders ? "bg-emerald-500" : "bg-red-500"}`} />{dashboard.data?.settings?.isAcceptingOrders ? "Recebendo pedidos" : "Pausado"}</div><OperationSettings settings={dashboard.data?.settings} /></div>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl bg-[#17120e] p-5 text-[#fffaf3]"><ClipboardList className="h-5 w-5 text-[#e9c98f]" /><p className="mt-7 text-sm text-[#c9bca9]">Pedidos hoje</p><p className="mt-1 font-display text-4xl font-bold">{values?.count ?? 0}</p></div><div className="rounded-2xl bg-[#fffdf8] p-5 shadow-[0_10px_26px_rgba(53,34,17,.06)]"><CircleDollarSign className="h-5 w-5 text-primary" /><p className="mt-7 text-sm text-muted-foreground">Faturamento concluído</p><p className="mt-1 font-display text-3xl font-bold">{money(Number(values?.revenueCents ?? 0))}</p></div><div className="rounded-2xl bg-[#fffdf8] p-5 shadow-[0_10px_26px_rgba(53,34,17,.06)]"><ShoppingBag className="h-5 w-5 text-primary" /><p className="mt-7 text-sm text-muted-foreground">Ticket médio</p><p className="mt-1 font-display text-3xl font-bold">{money(Math.round(Number(values?.averageTicketCents ?? 0)))}</p></div><div className="rounded-2xl bg-[#fffdf8] p-5 shadow-[0_10px_26px_rgba(53,34,17,.06)]"><Clock3 className="h-5 w-5 text-primary" /><p className="mt-7 text-sm text-muted-foreground">Tempo prometido</p><p className="mt-1 font-display text-3xl font-bold">{dashboard.data?.settings?.estimatedDeliveryMin}–{dashboard.data?.settings?.estimatedDeliveryMax}<span className="ml-1 text-base">min</span></p></div></div><div className="mt-9"><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-2xl font-bold">Pedidos recentes</h2><span className="text-sm text-muted-foreground">Atualizado agora</span></div><OrdersTable compact /></div></>;
}
