import { CartItem, useCart } from "@/contexts/CartContext";
import { Button } from "@/components/ui/button";
import { ArrowRight, Minus, Plus, ShoppingBag, X } from "lucide-react";
import { useLocation } from "wouter";

const money = (cents: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100);

export default function CartPanel({ onClose, deliveryFeeCents, onEdit }: { onClose: () => void; deliveryFeeCents: number; onEdit: (item: CartItem) => void }) {
  const [, setLocation] = useLocation();
  const { items, subtotalCents, updateQuantity, removeItem, itemCount } = useCart();
  return <aside className="pubx-cart-panel fixed inset-y-0 right-0 z-50 flex w-full max-w-md flex-col bg-[#fffdf8] shadow-2xl">
    <div className="flex items-center justify-between border-b px-6 py-5"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#b4472d]">Seu pedido</p><h2 className="font-display text-2xl font-bold">Sacola ({itemCount})</h2></div><button onClick={onClose} className="rounded-full p-2 hover:bg-[#f1eadf]" aria-label="Fechar sacola"><X className="h-5 w-5" /></button></div>
    <div className="flex-1 overflow-auto px-6 py-5">
      {items.length === 0 ? <div className="flex h-full flex-col items-center justify-center text-center"><ShoppingBag className="mb-4 h-9 w-9 text-[#c5aa86]" /><p className="font-display text-xl">Sua sacola está vazia.</p><p className="mt-2 text-sm text-muted-foreground">Explore o cardápio e escolha seus favoritos.</p></div> : <div className="space-y-5">{items.map(item => { const unit = item.basePriceCents + item.addons.reduce((sum, addon) => sum + addon.priceCents, 0); return <div key={item.id} className="border-b border-[#e5d9c8] pb-5"><div className="flex gap-3"><div className="h-16 w-16 overflow-hidden rounded-xl bg-[#e9dfd0]">{item.imageUrl && <img src={item.imageUrl} alt="" className="h-full w-full object-cover" />}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="font-semibold leading-tight">{item.name}</p><p className="font-semibold">{money(unit * item.quantity)}</p></div>{item.addons.map(addon => <p className="mt-1 text-xs text-muted-foreground" key={addon.id}>+ {addon.name}</p>)}{item.note && <p className="mt-1 text-xs italic text-muted-foreground">“{item.note}”</p>}<div className="mt-3 flex items-center justify-between"><div className="pubx-cart-quantity flex items-center gap-3 rounded-lg border bg-white px-1 py-1"><button onClick={() => updateQuantity(item.id, item.quantity - 1)} className="rounded-md p-1.5 hover:bg-[#f3ece1]" aria-label="Diminuir quantidade"><Minus className="h-3.5 w-3.5" /></button><span className="w-4 text-center text-sm font-semibold">{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.quantity + 1)} className="rounded-md p-1.5 hover:bg-[#f3ece1]" aria-label="Aumentar quantidade"><Plus className="h-3.5 w-3.5" /></button></div><div className="flex items-center gap-3"><button onClick={() => onEdit(item)} className="text-xs font-semibold text-[#6f5141] underline-offset-4 hover:underline">Editar</button><button onClick={() => removeItem(item.id)} className="text-xs font-semibold text-[#a93e28] underline-offset-4 hover:underline">Remover</button></div></div></div></div></div>; })}</div>}
    </div>
    {items.length > 0 && <div className="pubx-cart-summary border-t bg-[#fbf6ee] px-6 py-5"><div className="mb-2 flex justify-between text-sm"><span className="text-muted-foreground">Subtotal</span><strong>{money(subtotalCents)}</strong></div><div className="mb-4 flex justify-between text-sm"><span className="text-muted-foreground">Entrega</span><span>{deliveryFeeCents ? money(deliveryFeeCents) : "A calcular"}</span></div><div className="mb-5 flex justify-between border-t border-[#e5d9c8] pt-3"><span className="font-semibold">Total no delivery</span><strong className="text-lg text-[#b4472d]">{money(subtotalCents + deliveryFeeCents)}</strong></div><Button className="h-12 w-full rounded-xl bg-[#b4472d] text-base hover:bg-[#943722]" onClick={() => { onClose(); setLocation("/checkout"); }}>Continuar para checkout <ArrowRight className="ml-2 h-4 w-4" /></Button></div>}
  </aside>;
}
