import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { compressImageFile } from "@/lib/imageCompression";
import { copyToClipboard } from "@/lib/clipboard";
import { trpc } from "@/lib/trpc";
import { Check, Copy, ImagePlus, Loader2 } from "lucide-react";
import { ChangeEvent, useState } from "react";

export default function ProductImageUpload() {
  const [uploadedUrl, setUploadedUrl] = useState(""); const [error, setError] = useState(""); const [copied, setCopied] = useState(false);
  const upload = trpc.admin.uploadProductImage.useMutation({ onSuccess: data => { setUploadedUrl(data.url); setError(""); setCopied(false); } });
  const chooseFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const valid = ["image/jpeg", "image/png", "image/webp", "image/avif"]; if (!valid.includes(file.type) || file.size > 20_000_000) { setError("Escolha JPG, PNG, WEBP ou AVIF de até 20 MB."); event.target.value = ""; return; } setError(""); void compressImageFile(file).then(({ base64, contentType }) => { upload.mutate({ filename: file.name, contentType: contentType as "image/jpeg" | "image/png" | "image/webp" | "image/avif", dataBase64: base64 }); }); };
  const copy = async () => { await copyToClipboard(uploadedUrl); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  return <section className="mb-7 rounded-2xl border border-[#e0ceba] bg-[#fffaf4] p-5 shadow-[0_8px_24px_rgba(61,39,23,.05)]"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#f2e0d1] text-primary"><ImagePlus className="h-5 w-5" /></span><div><h2 className="font-display text-xl font-bold text-[#302119]">Imagem de produto</h2><p className="mt-1 max-w-2xl text-sm leading-5 text-[#6f5a4c]">No formulário de produto, você pode manter a **URL da imagem**. Ou envie um arquivo aqui, copie a URL gerada e cole no campo. São aceitos JPG, PNG, WEBP e AVIF de até 20 MB.</p></div></div><label className="inline-flex h-10 shrink-0 cursor-pointer items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-primary-hover"><ImagePlus className="h-4 w-4" />{upload.isPending ? "Enviando…" : "Enviar imagem"}<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={chooseFile} /></label></div>{upload.isPending ? <p className="mt-4 flex items-center gap-2 text-sm text-[#7b5645]"><Loader2 className="h-4 w-4 animate-spin" />Enviando imagem com qualidade original…</p> : null}{error || upload.error ? <p className="mt-4 text-sm text-red-700">{error || upload.error?.message}</p> : null}{uploadedUrl ? <div className="mt-4 grid gap-3 rounded-xl border border-[#e4d8c8] bg-white p-3 sm:grid-cols-[76px_1fr_auto]"><img src={uploadedUrl} alt="Prévia da imagem enviada" className="h-16 w-full rounded-lg object-cover sm:w-[76px]" /><div className="min-w-0"><Label>URL gerada para o produto</Label><Input readOnly value={uploadedUrl} className="mt-1.5 h-9 bg-[#fffdfa] text-xs" /></div><Button type="button" variant="outline" onClick={() => void copy()} className="h-9 self-end rounded-lg border-[#d8c7b0] bg-white">{copied ? <Check className="mr-1.5 h-4 w-4 text-emerald-700" /> : <Copy className="mr-1.5 h-4 w-4" />}{copied ? "Copiada" : "Copiar URL"}</Button></div> : null}</section>;
}
