import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { isMarcaBackground, MARCA_GRADIENT } from "@shared/colorThemes";
import { ArrowRight, Clock3, MapPin, Package } from "lucide-react";
import { useLocation } from "wouter";

export default function ServiceSection() {
  const [, setLocation] = useLocation();
  const settings = trpc.catalog.settings.useQuery();
  const marca = isMarcaBackground(settings.data?.customBackgroundColor);
  return <section className={`mm-service-section border-y py-14 sm:py-20 ${marca ? "border-white/10" : "border-[#dac8ae] bg-[#f1e6d7] text-[#231d18]"}`} style={marca ? { background: MARCA_GRADIENT } : undefined}><div className="page-shell"><div className="grid items-center gap-10 lg:grid-cols-[1.3fr_.7fr]"><div><p className={`text-xs font-bold uppercase tracking-[.18em] ${marca ? "text-[#e9c98f]" : "text-primary"}`}>Do pedido à sua mesa</p><h2 className={`mt-3 max-w-xl font-display text-4xl font-bold leading-tight sm:text-5xl ${marca ? "text-[#f5f5f0]" : ""}`}>Uma pausa gostosa começa com um pedido simples.</h2><p className={`mt-4 max-w-2xl leading-7 ${marca ? "text-[#d8dcea]" : "text-[#695b50]"}`}>Escolha entre delivery ou retirada, personalize seus itens e acompanhe cada etapa do preparo pelo telefone usado no pedido.</p><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="mm-service-card rounded-2xl bg-[#fffdf8] p-5 text-[#231d18] shadow-sm"><Clock3 className="h-5 w-5 text-primary" /><h3 className="mt-4 font-semibold">Preparo ágil</h3><p className="mt-1 text-sm leading-5 text-[#8a7a68]">Estimativa de 30 a 50 minutos.</p></div><div className="mm-service-card rounded-2xl bg-[#fffdf8] p-5 text-[#231d18] shadow-sm"><MapPin className="h-5 w-5 text-primary" /><h3 className="mt-4 font-semibold">Você escolhe</h3><p className="mt-1 text-sm leading-5 text-[#8a7a68]">Delivery ou retirada no balcão.</p></div><div className="mm-service-card rounded-2xl bg-[#fffdf8] p-5 text-[#231d18] shadow-sm"><Package className="h-5 w-5 text-primary" /><h3 className="mt-4 font-semibold">Acompanhe</h3><p className="mt-1 text-sm leading-5 text-[#8a7a68]">Consulte seu pedido pelo telefone.</p></div></div></div><aside className="rounded-3xl bg-[#201712] p-7 text-[#fffaf3] shadow-xl sm:p-8" style={marca ? { background: MARCA_GRADIENT } : undefined}><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e9c98f]">Pronto para pedir?</p><h3 className="mt-3 font-display text-3xl font-bold">Seu próximo sabor está aqui.</h3><p className="mt-3 text-sm leading-6 text-[#d8c8b5]">Veja o cardápio, ajuste seus adicionais e finalize com poucos passos.</p><div className="mt-7 grid gap-3"><Button onClick={() => document.getElementById("cardapio")?.scrollIntoView({ behavior: "smooth" })} className="h-11 rounded-xl bg-primary hover:bg-primary-hover-light" style={marca ? { background: MARCA_GRADIENT } : undefined}>Ver cardápio <ArrowRight className="ml-2 h-4 w-4" /></Button><Button variant="outline" onClick={() => setLocation("/acompanhar")} className="h-11 rounded-xl border-[#6d5846] bg-transparent text-[#fffaf3] hover:bg-[#30241d] hover:text-white">Acompanhar pedido</Button></div></aside></div></div></section>;
}
